name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libdrm-dev

    - name: Build FTXUI
      run: |
        git clone https://github.com/ArthurSonzogni/FTXUI.git
        cd FTXUI
        mkdir -p build && cd build
        cmake .. -DFTXUI_BUILD_EXAMPLES=OFF -DFTXUI_BUILD_DOCS=OFF
        make -j$(nproc)
        sudo make install
        sudo ldconfig

    - name: Build amdgpu-top
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j$(nproc)

    - name: Prepare debian package
      run: |
        mkdir -p debian/usr/bin
        cp build/amdgpu-top debian/usr/bin/
        chmod +x debian/DEBIAN/postinst
        dpkg-deb --build debian
        mv debian.deb amdgpu-top_0.1.0_amd64.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: amdgpu-top-deb
        path: amdgpu-top_0.1.0_amd64.deb

    - name: Upload Release Asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: amdgpu-top_0.1.0_amd64.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 